# Listen on the standard MQTT port on all interfaces
listener 1883

# Enable WebSocket connections on port 9001
listener 9001
protocol websockets

# Persist session and message data to disk
persistence true
persistence_location /mosquitto/data/

# Log to file and stdout
log_dest file /mosquitto/log/mosquitto.log
log_dest stdout
log_type all

# Enable unauthenticated users
allow_anonymous true

# Provide faster interval for sys messages used for healthchecks
sys_interval 1