services:
  world:
    build: ./world
    environment:
      - AWS_ENDPOINT_OVERRIDE=http://localstack:4566
    depends_on:
      localstack:
        condition: service_healthy
  gateway:
    build: ./gateway
    environment:
      - AWS_ENDPOINT_OVERRIDE=http://localstack:4566
    depends_on:
      localstack:
        condition: service_healthy
  localstack:
    container_name: localstack
    image: localstack/localstack
    ports:
      - '127.0.0.1:4566:4566' # LocalStack Gateway
      - '127.0.0.1:4510-4559:4510-4559' # external services port range
      - '127.0.0.1:443:443' # LocalStack HTTPS Gateway
    environment:
      - LOCALSTACK_AUTH_TOKEN=${LOCALSTACK_AUTH_TOKEN:?} # required for Pro
    healthcheck:
      test: [ "CMD-SHELL", "curl -s http://localhost:4566/_localstack/init/ready | grep -q '\"completed\":[[:space:]]*true'" ]
      interval: 5s
      timeout: 5s
      retries: 30
      start_period: 30s
    volumes:
      - ./localstack/init.sh:/etc/localstack/init/ready.d/init-aws.sh
