services:
  mosquitto:
    image: eclipse-mosquitto
    container_name: mosquitto
    ports:
      - "1883:1883" # Standard MQTT port
      - "9001:9001" # MQTT over WebSocket
    volumes:
      - ./mosquitto/config:/mosquitto/config
      - ./mosquitto/data:/mosquitto/data # Persistent message storage
      - ./mosquitto/log:/mosquitto/log